<a href="https://colab.research.google.com/github/ChandrikaRongala/AI_ML_Avanthi_Chandrika/blob/main/Day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
a =np.array([1,2,3])
print (a)

[1 2 3]


In [5]:
import numpy as np
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print (b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
a.size

3

In [7]:
#get size
a=np.array([1,2,3],dtype='int64')
a.itemsize

8

In [12]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
#to get a specific element[r,c]
a[1,5]

13

In [10]:
#to get a specific row
a[:,2]

array([ 3, 10])

In [13]:
a[0,1:-1:2]

array([2, 4, 6])

In [14]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [15]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
Initialising different types of arrays

In [21]:
#all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#all 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [23]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [25]:
a=np.array([[1,2,3,4,],[2,3,4,5,]])
print(a)

[[1 2 3 4]
 [2 3 4 5]]


In [26]:
#any other number(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])